apiVersion: training.exalsius.ai/v1
kind: DDPJob
metadata:
  name: cpu-test-job
spec:
  # The job should run on one (or more) of these GPUs
  gpuTypes:
    - A100
    - RTXA6000
  # We want to run the job on 2 nodes
  parallelism: 2
  # each node should have 1 GPU
  nprocPerNode: 1  # Use 1 GPUs per node (pod)
  # Use the following container image
  image: <image-name>:<image-tag>
  # The path to the script to run
  scriptPath: "/app/diloco_training/training/diloco_trainer.py"
  # The API key for Weights and Biases
  #wandbApiKey: "XXXXXXXXX"
  # The arguments to pass to the script
  args:
    - "--per_device_train_batch_size"
    - "2"
    - "--batch_size"
    - "4"
    - "--warmup_steps"
    - "50"
    - "--local_steps"
    - "10"
    - "--total_steps"
    - "20"
    - "--model"
    - "gpt-neo-tiny"
    - "--dataset"
    - "test_squence_dataset"
    - "--device"
    - "cpu"

