diloco:
  model: "gpt-neo-x"
  dataset: "c4"
  localSteps: "128"
  lr: "4e-4"
  outerLr: "0.7"
  warmupSteps: "1000"
  totalSteps: "30000"
  perDeviceTrainBatchSize: "32"
  batchSize: "512"
  optimMethod: "sgd"
  quantization: "false"
  checkpointPath: "checkpoint.pth"
  checkpointInterval: "512"
  device: "cuda"
  heterogeneous: "false"
  compressionDecay: "0.9"
  compressionTopk: "32"
  experimentDescription: "DiLoCo distributed training experiment"
  experimentTags: '["diloco", "gpt-neo-x", "c4"]'
  seed: "42"
